name: Build MacOS

on:
  push:
    branches-ignore:
      - 'coverityScan'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11
          - macos-12
        build_opts:
          - ''
        include:
          - os: macos-latest
            build_opts: '-Db_lto=true -Ddefault_library=static'
      fail-fast: false
    steps:
      - name: Runtime environment
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "GITHUB_WORKSPACE=`pwd`" >> $GITHUB_ENV
      - name: Setup Meson + Ninja + gcovr
        shell: bash
        run: |
          brew install meson ninja gcovr
        working-directory: ${{ runner.temp }}
      - name: Version tools
        shell: bash
        run: |
          cc --version || true
          ld --version || true
          gcov --version || true
          meson --version
          ninja --version
      - name: Checkout rSON
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      - name: Configure
        run: meson setup build --prefix=$HOME/.local ${{ matrix.build_opts }}
      - name: Build
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Run coverage build
        if: github.repository == 'dragonmux/rSON'
        # Codecov no longer parses gcov files automatically
        run: |
          meson setup cov-build --prefix=$HOME/.local -Db_coverage=true --buildtype=debug
          meson compile -C cov-build
          meson test -C cov-build
          ninja -C cov-build coverage-xml
      - name: Install
        run: meson install -C build
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os }}-appleclang
          path: |
            ${{ github.workspace }}/build/meson-logs/*
            ${{ github.workspace }}/cov-build/meson-logs/*
          retention-days: 5
      - name: Codecov
        if: success() && github.repository == 'dragonmux/rSON'
        uses: codecov/codecov-action@v3
        with:
          directory: ./cov-build/meson-logs
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  build-macos-homebrew:
    # Apple LLD is unable to link GCC < 11 generated object files.
    # https://stackoverflow.com/questions/73714336/xcode-update-to-version-2395-ld-compile-problem-occurs-computedatomcount-m
    # rdar://FB11369327
    name: '${{ matrix.os }} (homebrew, ${{ matrix.compiler }})'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11
        compiler:
          # GCC5 cannot compile anything on macOS
          # - gcc@5
          ## GCC6 cannot handle constexpr-ness of mmap_t
          ## See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66297
          # - gcc@6
          # GCC7 doesn't provide <filesystem> required by substrate in C++17 mode
          #- gcc@7
          - gcc@8
          - gcc@9
          - gcc@10
          - gcc@11
          - gcc@12
          - gcc@13
      fail-fast: false
    steps:
      - name: Runtime environment
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "GITHUB_WORKSPACE=`pwd`" >> $GITHUB_ENV
      - name: Setup compiler
        shell: bash
        run: |
          brew install ${{ matrix.compiler }} gcovr
          CC=${COMPILER/@/-}
          CXX=${CC/#gcc/g++}
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CXX=$CXX" >> $GITHUB_ENV
          echo "GCOV=${CC/#gcc/gcov}" >> $GITHUB_ENV
        env:
          COMPILER: ${{ matrix.compiler }}
      - name: Checkout rSON
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      - name: Setup Meson + Ninja
        shell: bash
        run: |
          brew install meson ninja
        working-directory: ${{ runner.temp }}
      - name: Version tools
        shell: bash
        run: |
          $CC --version
          $CXX --version
          $GCOV --version
          meson --version
          ninja --version
      - name: Configure
        run: meson setup build --prefix=$HOME/.local $BUILD_OPTS
      - name: Build
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Run coverage build
        if: github.repository == 'dragonmux/rSON'
        # Codecov no longer parses gcov files automatically
        run: |
          meson setup cov-build --prefix=$HOME/.local --buildtype=debug -Db_coverage=true
          meson compile -C cov-build
          meson test -C cov-build
          ninja -C cov-build coverage-xml
      - name: Install
        run: meson install -C build
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os }}-homebrew-${{ matrix.compiler }}
          path: |
            ${{ github.workspace }}/build/meson-logs/*
            ${{ github.workspace }}/cpv-build/meson-logs/*
          retention-days: 5
      - name: Codecov
        if: success() && github.repository == 'dragonmux/rSON'
        uses: codecov/codecov-action@v3
        with:
          directory: ./cov-build/meson-logs
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
